*****************************************************************************************************************;
*                                                                                                               *;
*; %let pgm=cst_200;                                                                                            *;
*                                                                                                               *;
*  OPSYS  WIN 10 64bit SAS 9.4M6(64bit)  (This code will not run in lockdown)                                   *;
*                                                                                                               *;
*; %let purpose=Sum columns 1 thru 4 in worksheet G0;                                                          ;*;
*                                                                                                               *;
*  Github repository (sample input, output and code is at)                                                      *;
*                                                                                                               *;
*  https://github.com/rogerjdeangelis/CostReports                                                               *;
*                                                                                                               *;
*  PROJECT TOKEN = cst                                                                                          *;
*                                                                                                               *;
*  This is the third  module in the Cost Report Project                                                         *;
*                                                                                                               *;
*; %let _r=d; * home directory;                                                                                ;*;
*                                                                                                               *;
*;libname cst "&_r:/cst"; /* Where the schema tables and intermediary tables is stored */                       *;
*;libname  cstfmt "&_r:/cst/fmt";                                                                               *;
*                                                                                                               *;
*; options fmtsearch=(work.formats cst.cst_fmtv1a) sasautos="&_r:/oto" ;                                        *;
*                                                                                                               *;
*                                                                                                               *;
* INTERNAL MACROS                                                                                               *;
* ===============                                                                                               *;
*                                                                                                               *;
*  cst_200 - first module in cost report analysis                                                               *;
*                                                                                                               *;
* EXTERNAL MACROS IN AUTOCALL LIBRARY                                                                           *;
* ====================================                                                                          *;
*                                                                                                               *;
*  INPUTS (works for all cost reports here is input for SNF)                                                    *;
*  =========================================================                                                    *;
*                                                                                                               *;
*  The cost report token (example)                                                                              *;
*  The years to process must be sequential                                                                      *;
*                                                                                                               *;
*  typ    = snf                                                                                                 *;
*  yrs    = 2011-2019                                                                                           *;
*                                                                                                               *;
*  Output from cst_150 macro (2011-201 SNF all data from all CSVs(                                              *;
*                                                                                                               *;
*  &_r:\cst\CST_150SNFNUMALP20112019.sas7bdat                                                                   *;
*                                                                                                               *;
*  PROCESS                                                                                                      *;
*  =======                                                                                                      *;
*                                                                                                               *;
*    1. Check status of previous module, cst_150.                                                               *;
*                                                                                                               *;
*       If previous module executed without error then this table will exist                                    *;
*                                                                                                               *;
*       &_r:\cst\cst_150.sas7badat                                                                              *;
*                                                                                                               *;
*       else                                                                                                    *;
*                                                                                                               *;
*       it will not exist                                                                                       *
*                                                                                                               *;
*       If it does not exist go into sytax check mode                                                           *;
*                                                                                                               *;
*    2. Sum columns 1-4 in G0 worksheet and add create column 5                                                 *;
*                                                                                                               *;
*       example (creates a worksheet column 5 that does not exist in original work sheet)                       *;
*                                                                                                               *;
*        Worsheet Line                                                                                          *;
*                                                                                                               *;
*        G000000_01200_00500 =                                                                                  *;
*                                                                                                               *;
*         G000000_01200_00100 +                                                                                 *;
*         G000000_01200_00200 +                                                                                 *;
*         G000000_01200_00300 +                                                                                 *;
*         G000000_01200_00400                                                                                   *;
*                                                                                                               *;
*                                                                                                               *;
*  OUTPUTS (works for all cost reports here is input for SNF)                                                   *;
*  =========================================================                                                    *;
*                                                                                                               *;
*  1. Skinny fact table with addded column 5 in G0 worksheet                                                    *;
*                                                                                                               *;
*      &_r:\cst\CST_200SnfFiv20112019.sas7bdat                                                                  *;
*                                                                                                               *;
*  2. One record with the max value for every cell for all Years of SNF                                         *;
*                                                                                                               *;
*      &_r:\cst\CST_200SnfMax20112019.sas7bdat                                                                  *;
*                                                                                                               *;
*  3. If code ran sucessfully create sas table                                                                  *;
*                                                                                                               *;
*     &_r:\cst\CST_200.sas7bdat                                                                                 *;
*                                                                                                               *;
*                                                                                                               *;
*****************************************************************************************************************;
*                                                                                                               *;
* CHANGE HISTORY                                                                                                *;
*                                                                                                               *;
*  1. Roger Deangelis              19JMAY2019   Creation                                                        *;
*     rogerjdeangelis@gamil.com                                                                                 *;
*                                                                                                               *;
*****************************************************************************************************************;
